"""Guards the "stream interrupted" placeholder shown when a camera the user is watching stops.

The placeholder is committed, architecture-independent static data (a JPEG for MJPEG + snapshot, a
one-frame annexb H264 keyframe compiled into stream-webrtc), regenerated by
assets/generate-placeholder.sh. These tests lock the bytes' validity (a malformed H264 frame would
not decode in the browser, the whole point) and that all three transports are wired to surface it.
"""
import re
from pathlib import Path

CAMERA_DIR = Path(__file__).resolve().parent.parent
SHIPPED_JPEG = CAMERA_DIR / "plugin" / "files" / "html" / "placeholder.jpg"
SOURCE_JPEG = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-http" / "html" / "placeholder.jpg"
H264_HEADER = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-webrtc" / "placeholder_h264.h"
WEBRTC_SERVER = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-webrtc" / "main.cpp"
CAMERA_STREAM = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-http" / "camera-stream.py"
GENERATOR = CAMERA_DIR / "assets" / "generate-placeholder.sh"

JPEG_SOI = b"\xff\xd8"
JPEG_EOI = b"\xff\xd9"
NAL_SPS = 7
NAL_IDR = 5


def _header_bytes():
    body = H264_HEADER.read_text(encoding="utf-8").split("{", 1)[1].rsplit("}", 1)[0]
    return bytes(int(token, 16) for token in re.findall(r"0x[0-9a-fA-F]{2}", body))


def _nal_types_via_long_start_codes(data):
    types = []
    index = 0
    while index < len(data) - 4:
        if data[index:index + 4] == b"\x00\x00\x00\x01":
            types.append(data[index + 4] & 0x1F)
            index += 4
        else:
            index += 1
    return types


# ── JPEG asset (MJPEG + snapshot) ──────────────────────────────────────────────────────────────

def test_placeholder_jpeg_is_a_valid_image():
    data = SHIPPED_JPEG.read_bytes()
    assert data.startswith(JPEG_SOI)
    assert data.endswith(JPEG_EOI)


def test_placeholder_jpeg_shipped_and_source_copies_match():
    # camera-stream.py runs from either dir depending on dev vs installed; keep the two in sync.
    assert SHIPPED_JPEG.read_bytes() == SOURCE_JPEG.read_bytes()


# ── H264 asset (WebRTC) ────────────────────────────────────────────────────────────────────────

def test_placeholder_h264_is_an_annexb_keyframe():
    data = _header_bytes()
    assert data.startswith(b"\x00\x00\x00\x01"), "must open on a 4-byte start code"
    types = _nal_types_via_long_start_codes(data)
    # Both the capture feed and the RTP packetizer (LongStartSequence) split on 4-byte codes only,
    # so every NAL must be reachable that way, and the frame must be self-contained (its own SPS +
    # IDR).
    assert NAL_SPS in types, f"no SPS among 4-byte-delimited NALs: {types}"
    assert NAL_IDR in types, f"no IDR among 4-byte-delimited NALs: {types}"


def test_placeholder_h264_header_is_self_contained():
    text = H264_HEADER.read_text(encoding="utf-8")
    assert "placeholder_h264[]" in text
    assert "placeholder_h264_len" in text


# ── wiring: all three transports surface it ────────────────────────────────────────────────────

def test_webrtc_server_surfaces_the_placeholder():
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert '#include "placeholder_h264.h"' in text
    # shown while the feed is down past the stall threshold...
    assert "maybe_send_placeholder" in text
    assert "PLACEHOLDER_AFTER_MS" in text
    # ...and once before a deliberate teardown (recycle/pong timeout) so the close is not a freeze.
    assert "send_placeholder_to" in text


def test_webrtc_deliberate_close_is_deferred_so_the_placeholder_lands():
    # An immediate pc->close() after sending the placeholder drops the queued keyframe and the tile
    # freezes on its last live frame. The close must be deferred (placeholder, stop live frames,
    # flush, then close).
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert "PLACEHOLDER_FLUSH_MS" in text
    assert "begin_close" in text and "advance_close" in text
    # a closing client gets no more live frames (they would overwrite the message before teardown)
    assert "if (client->closing)" in text
    # the old immediate "send_placeholder_to(c); c->pc->close();" recycle path must be gone
    assert "send_placeholder_to(c);\n                c->pc->close();" not in text


def test_camera_stream_surfaces_the_placeholder():
    text = CAMERA_STREAM.read_text(encoding="utf-8")
    assert "load_placeholder" in text
    assert "CAPTURE_STALLED" in text          # MJPEG: relay placeholder on a prolonged stall
    assert "placeholder_jpeg" in text          # snapshot: serve placeholder when capture is down


def test_placeholder_generator_is_committed():
    # the bytes are committed, but their provenance (regeneration recipe) must travel with the repo
    assert GENERATOR.is_file()
