"""Guards the two splash screens a viewer sees in place of live video.

"Connecting..." covers the wait while a viewer's stream comes up, "Stream interrupted" covers a
stream that stops after the viewer has had picture. Each is committed, architecture-independent
static data (a JPEG for MJPEG + snapshot, a one-frame annexb H264 keyframe compiled into
stream-webrtc), regenerated by assets/generate-splash.sh. These tests lock the bytes' validity (a
malformed H264 frame would not decode in the browser, the whole point) and that every transport is
wired to surface both.
"""
import re
from pathlib import Path

import pytest

CAMERA_DIR = Path(__file__).resolve().parent.parent
SHIPPED_HTML = CAMERA_DIR / "plugin" / "files" / "html"
SOURCE_HTML = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-http" / "html"
WEBRTC_DIR = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-webrtc"
WEBRTC_SERVER = WEBRTC_DIR / "main.cpp"
CAMERA_STREAM = CAMERA_DIR / "src" / "v4l2-mpp" / "apps" / "stream-http" / "camera-stream.py"
GENERATOR = CAMERA_DIR / "assets" / "generate-splash.sh"

SPLASH_NAMES = ("connecting", "interrupted")

JPEG_SOI = b"\xff\xd8"
JPEG_EOI = b"\xff\xd9"
NAL_SPS = 7
NAL_IDR = 5


def _header_bytes(splash_name):
    header = WEBRTC_DIR / f"{splash_name}_h264.h"
    body = header.read_text(encoding="utf-8").split("{", 1)[1].rsplit("}", 1)[0]
    return bytes(int(token, 16) for token in re.findall(r"0x[0-9a-fA-F]{2}", body))


def _named_number(text, constant_name):
    declaration = re.search(rf"\b{constant_name}\s*=\s*([0-9.]+)", text)
    assert declaration, f"{constant_name} is not declared"
    return float(declaration.group(1))


def _nal_types_via_long_start_codes(data):
    types = []
    index = 0
    while index < len(data) - 4:
        if data[index:index + 4] == b"\x00\x00\x00\x01":
            types.append(data[index + 4] & 0x1F)
            index += 4
        else:
            index += 1
    return types


# ── JPEG assets (MJPEG + snapshot) ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize("splash_name", SPLASH_NAMES)
def test_splash_jpeg_is_a_valid_image(splash_name):
    data = (SHIPPED_HTML / f"{splash_name}.jpg").read_bytes()
    assert data.startswith(JPEG_SOI)
    assert data.endswith(JPEG_EOI)


@pytest.mark.parametrize("splash_name", SPLASH_NAMES)
def test_splash_jpeg_shipped_and_source_copies_match(splash_name):
    # camera-stream.py runs from either dir depending on dev vs installed; keep the two in sync.
    shipped = (SHIPPED_HTML / f"{splash_name}.jpg").read_bytes()
    assert shipped == (SOURCE_HTML / f"{splash_name}.jpg").read_bytes()


def test_the_two_splashes_carry_different_messages():
    # identical bytes would mean a viewer is told to refresh a page that is merely still starting,
    # which is the confusion these two assets exist to remove
    connecting = (SHIPPED_HTML / "connecting.jpg").read_bytes()
    assert connecting != (SHIPPED_HTML / "interrupted.jpg").read_bytes()
    assert _header_bytes("connecting") != _header_bytes("interrupted")


# ── H264 assets (WebRTC) ───────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("splash_name", SPLASH_NAMES)
def test_splash_h264_is_an_annexb_keyframe(splash_name):
    data = _header_bytes(splash_name)
    assert data.startswith(b"\x00\x00\x00\x01"), "must open on a 4-byte start code"
    types = _nal_types_via_long_start_codes(data)
    # Both the capture feed and the RTP packetizer (LongStartSequence) split on 4-byte codes only,
    # so every NAL must be reachable that way, and the frame must be self-contained (its own SPS +
    # IDR).
    assert NAL_SPS in types, f"no SPS among 4-byte-delimited NALs: {types}"
    assert NAL_IDR in types, f"no IDR among 4-byte-delimited NALs: {types}"


@pytest.mark.parametrize("splash_name", SPLASH_NAMES)
def test_splash_h264_header_is_self_contained(splash_name):
    text = (WEBRTC_DIR / f"{splash_name}_h264.h").read_text(encoding="utf-8")
    assert f"{splash_name}_h264[]" in text
    assert f"{splash_name}_h264_len" in text


# ── wiring: every transport surfaces the right one ─────────────────────────────────────────────

def test_webrtc_server_surfaces_both_splashes():
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert '#include "connecting_h264.h"' in text
    assert '#include "interrupted_h264.h"' in text
    # shown while that viewer is without picture past its threshold...
    assert "maybe_send_splash" in text
    assert "CONNECTING_AFTER_SILENT_MS" in text
    assert "INTERRUPTED_AFTER_SILENT_MS" in text
    # ...and once before the server tears the stream down itself (recycle/pong timeout), so that
    # close reads as a message rather than a freeze.
    assert "send_closing_splash_to" in text


def test_webrtc_picks_the_splash_per_viewer_not_globally():
    # a viewer that never had picture is still connecting; a viewer that lost picture is
    # interrupted. A shared flag would tell a fresh viewer to refresh the page.
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert "seen_live_frame" in text
    assert "GIVE_UP_CONNECTING_MS" in text
    # each viewer's silence is its own, so joining a camera someone else is watching still says
    # connecting, and a viewer whose video is flowing is left alone
    assert "last_live_frame" in text
    assert "Splash::Quiet" in text


def test_webrtc_counts_a_viewer_as_watching_only_once_it_can_decode():
    # The camera sends a keyframe every couple of seconds. A viewer that arrives in between is
    # handed frames that reference a picture it never received: it has bytes on the wire and a black
    # tile on screen. Counting those as "watching" is what kept the connecting splash hidden.
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert "frame_carries_keyframe" in text
    assert "client->seen_live_frame = true" in text
    guarded = "if (carries_keyframe) {\n        client->seen_live_frame = true;"
    assert guarded in text
    # the old "any frame that left the socket means this viewer has picture" wiring must be gone
    sent_is_seen = "if (send_to_client(client, now, data, size)) {\n        client->seen_live_frame"
    assert sent_is_seen not in text


def test_webrtc_reads_the_frame_once_and_only_while_someone_lacks_a_picture():
    # scanning the frame's bytes per viewer per frame is the same answer computed again for every
    # viewer, and once they all have a picture the answer is not used at all
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    hoisted = "any_client_awaits_first_picture() && frame_carries_keyframe(data, size)"
    assert hoisted in text
    assert text.count("frame_carries_keyframe(data, size)") == 1


@pytest.mark.parametrize("splash_name", ["connecting", "interrupted"])
def test_the_keyframe_rule_recognizes_a_real_keyframe(splash_name):
    # the rule the server scans by (an IDR or an SPS NAL), checked against keyframes we ship rather
    # than against a hand-written example that could agree with a wrong rule
    types = _nal_types_via_long_start_codes(_header_bytes(splash_name))
    assert 5 in types or 7 in types


@pytest.mark.parametrize("webrtc_name,mjpeg_name", [
    ("CONNECTING_AFTER_SILENT_MS", "CONNECTING_AFTER_SILENT_S"),
    ("INTERRUPTED_AFTER_SILENT_MS", "INTERRUPTED_AFTER_SILENT_S"),
    ("GIVE_UP_CONNECTING_MS", "GIVE_UP_CONNECTING_S"),
])
def test_both_transports_change_message_at_the_same_moment(webrtc_name, mjpeg_name):
    # the same camera is told two different stories otherwise, depending on which stream the tile
    # happens to use
    webrtc_ms = _named_number(WEBRTC_SERVER.read_text(encoding="utf-8"), webrtc_name)
    mjpeg_s = _named_number(CAMERA_STREAM.read_text(encoding="utf-8"), mjpeg_name)
    assert webrtc_ms == mjpeg_s * 1000


def test_webrtc_server_started_close_is_deferred_so_the_splash_lands():
    # An immediate pc->close() after sending the splash drops the queued keyframe and the tile
    # freezes on its last live frame. The close must be deferred (splash, stop live frames, flush,
    # then close).
    text = WEBRTC_SERVER.read_text(encoding="utf-8")
    assert "SPLASH_FLUSH_MS" in text
    assert "begin_close" in text and "advance_close" in text
    # a closing client gets no more live frames (they would overwrite the message before teardown)
    assert "if (client->closing)" in text
    # the old immediate "send_splash_to(c); c->pc->close();" recycle path must be gone
    assert "send_splash_to(c);\n                c->pc->close();" not in text


def test_camera_stream_surfaces_both_splashes():
    text = CAMERA_STREAM.read_text(encoding="utf-8")
    assert "load_splashes" in text
    assert "splash_for_silence" in text        # MJPEG: which message a silent feed earns
    assert "CAPTURE_CONNECTING" in text
    assert "CAPTURE_INTERRUPTED" in text
    assert "splash_jpegs" in text              # snapshot: serve a message when capture is down


def test_splash_generator_is_committed():
    # the bytes are committed, but their provenance (regeneration recipe) must travel with the repo
    assert GENERATOR.is_file()
