#!/bin/sh
# Regenerate the "Stream interrupted" placeholder shown to a camera viewer when the live feed stalls
# or is torn down, so the tile carries a clear message instead of a frozen frame.
#
# It produces TWO artifacts from one rendered message image:
#   - placeholder.jpg   for the MJPEG stream + the snapshot endpoint (read by camera-stream.py)
#   - placeholder_h264.h a one-frame annexb H264 keyframe (SPS+PPS+IDR) compiled into stream-webrtc
#
# The outputs are committed, NOT built in the arm64 toolchain: the text is fixed and universal and the
# encoded bytes are architecture-independent (a JPEG and an H264 elementary stream decode identically
# everywhere), so baking ffmpeg/libx264 into the QEMU-emulated Docker build would only add weight and
# ship bytes nobody decode-tested. Run this on a dev host (needs ImageMagick + ffmpeg with libx264),
# eyeball placeholder.jpg, and confirm the H264 decodes in Chromium + WebKit before committing.
set -e

ASSETS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$ASSETS_DIR")"

SHIPPED_HTML="$REPO_DIR/plugin/files/html"
SOURCE_HTML="$REPO_DIR/src/v4l2-mpp/apps/stream-http/html"
WEBRTC_DIR="$REPO_DIR/src/v4l2-mpp/apps/stream-webrtc"

WIDTH=1280
HEIGHT=720
BACKGROUND="#1b1f24"
TITLE_COLOR="#e8eaed"
SUBTITLE_COLOR="#9aa3ad"
TITLE="Stream interrupted"
SUBTITLE="Refresh the page to restart it"

for cmd in magick ffmpeg xxd; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: '$cmd' is required." >&2; exit 1; }
done

# A sans-serif font, resolved portably: an explicit PLACEHOLDER_FONT (name or path) wins, else the
# first system font file that exists on this host (macOS / common Linux), so the script runs without
# arguments on either.
resolve_font() {
  if [ -n "$PLACEHOLDER_FONT" ]; then echo "$PLACEHOLDER_FONT"; return; fi
  for candidate in \
    /System/Library/Fonts/Supplemental/Arial.ttf \
    /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \
    /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf; do
    [ -f "$candidate" ] && { echo "$candidate"; return; }
  done
  echo "ERROR: no font found; set PLACEHOLDER_FONT to a .ttf path." >&2
  exit 1
}
FONT="$(resolve_font)"

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT
master_png="$work_dir/placeholder.png"
master_h264="$work_dir/placeholder.h264"

echo "==> Rendering message image (${WIDTH}x${HEIGHT})"
magick -size "${WIDTH}x${HEIGHT}" "canvas:${BACKGROUND}" \
  -gravity center \
  -font "$FONT" -pointsize 72 -fill "$TITLE_COLOR" -annotate +0-40 "$TITLE" \
  -font "$FONT" -pointsize 38 -fill "$SUBTITLE_COLOR" -annotate +0+55 "$SUBTITLE" \
  "$master_png"

echo "==> Writing placeholder.jpg"
magick "$master_png" -quality 90 "$SHIPPED_HTML/placeholder.jpg"
cp "$SHIPPED_HTML/placeholder.jpg" "$SOURCE_HTML/placeholder.jpg"

# baseline profile + yuv420p + a single IDR keyframe = the broadest-compatibility decode path and a
# self-contained frame, so a viewer whose live stream was a different size still re-inits on the SPS.
echo "==> Encoding one-frame annexb H264 keyframe"
ffmpeg -y -loglevel error -loop 1 -i "$master_png" -frames:v 1 \
  -c:v libx264 -profile:v baseline -level 3.1 -pix_fmt yuv420p \
  -x264-params keyint=1:scenecut=0:annexb=1 \
  -f h264 "$work_dir/raw.h264"

# Normalize every NAL to a 4-byte start code. x264 emits a 3-byte (00 00 01) code before the IDR
# slice, but both the capture feed (h264_frames.h only matches 00 00 00 01) and the RTP packetizer
# (Separator::LongStartSequence) split on 4-byte codes only, so a 3-byte-prefixed NAL would be
# mis-split and reach the browser malformed.
echo "==> Normalizing NAL start codes to 4 bytes"
python3 - "$work_dir/raw.h264" "$master_h264" <<'PY'
import sys

data = open(sys.argv[1], "rb").read()
starts = []
index = 0
while index < len(data) - 2:
    if data[index] == 0 and data[index + 1] == 0 and data[index + 2] == 1:
        starts.append(index)
        index += 3
    else:
        index += 1

out = bytearray()
for position, start in enumerate(starts):
    payload_start = start + 3
    payload_end = starts[position + 1] if position + 1 < len(starts) else len(data)
    if payload_end < len(data) and data[payload_end - 1] == 0:
        payload_end -= 1  # the trailing 0x00 belongs to the next NAL's 4-byte start code
    out += b"\x00\x00\x00\x01" + data[payload_start:payload_end]

open(sys.argv[2], "wb").write(out)
PY

echo "==> Emitting placeholder_h264.h"
header="$WEBRTC_DIR/placeholder_h264.h"
{
  echo "#pragma once"
  echo ""
  echo "#include <stdint.h>"
  echo "#include <stddef.h>"
  echo ""
  echo "// Pre-encoded H264 keyframe (annexb SPS+PPS+IDR) of the \"Stream interrupted\" message, sent to a"
  echo "// WebRTC viewer when the live feed stalls or before a deliberate session close so the tile shows a"
  echo "// clear message instead of a frozen frame. Generated by assets/generate-placeholder.sh and"
  echo "// committed: the bytes are fixed, universal, and architecture-independent, so there is no"
  echo "// build-time encoder dependency. Do not hand-edit; rerun the generator instead."
  echo "static const uint8_t placeholder_h264[] = {"
  xxd -i < "$master_h264"
  echo "};"
  echo "static const size_t placeholder_h264_len = sizeof(placeholder_h264);"
} > "$header"

echo ""
echo "Done:"
echo "  $SHIPPED_HTML/placeholder.jpg  ($(wc -c < "$SHIPPED_HTML/placeholder.jpg") bytes)"
echo "  $SOURCE_HTML/placeholder.jpg"
echo "  $header  (H264 $(wc -c < "$master_h264") bytes)"
